//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterprisesDataAcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class App_EnterprisesEntities : DbContext
    {
        public App_EnterprisesEntities()
            : base("name=App_EnterprisesEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enterprise_type> enterprise_type { get; set; }
        public virtual DbSet<enterprises> enterprises { get; set; }
        public virtual DbSet<investor> investor { get; set; }
        public virtual DbSet<portfolio> portfolio { get; set; }
    }
}
