//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterprisesDataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class investor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public investor()
        {
            this.portfolio = new HashSet<portfolio>();
        }
    
        public int id { get; set; }
        public string investor_name { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string balance { get; set; }
        public string photo { get; set; }
        public Nullable<int> portifolio_id { get; set; }
        public Nullable<int> portifolio_value { get; set; }
        public Nullable<byte> first_acess { get; set; }
        public Nullable<byte> super_angel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portfolio> portfolio { get; set; }
    }
}
