//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterprisesDataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class portfolio
    {
        public int id { get; set; }
        public Nullable<int> enterprise_id { get; set; }
        public Nullable<int> investor_id { get; set; }
    
        public virtual enterprises enterprises { get; set; }
        public virtual investor investor { get; set; }
    }
}
